name: runelite
base: core22
title: RuneLite
version: git
summary: A popular free, open-source and super fast client for Old School RuneScape
description: |
  A popular free, open-source and super fast client for Old School RuneScape

type: app
grade: stable
confinement: strict
icon: snap/gui/runelite.png
license: BSD-2-Clause
compression: lzo

parts:
  adoptopenjdk:
    plugin: dump
    source: https://github.com/adoptium/temurin11-binaries/releases/download/jdk-11.0.22%2B7/OpenJDK11U-jre_x64_linux_hotspot_11.0.22_7.tar.gz
    source-checksum: "sha256/3a0fec1b9ef38d6abd86cf11f6001772b086096b6ec2588d2a02f1fa86b2b1de"
    stage-packages:
      - libxi6
      - libxrender1
      - libxtst6

  runelite:
    plugin: nil # Cannot use dump due to limited source-type support
    build-packages: 
      - wget
    stage-packages:
      - libglu1-mesa
      - libpulse0
      - libasound2
      - libasound2-plugins
      - libnotify-bin
    override-pull: |
      wget https://github.com/runelite/launcher/releases/download/2.6.10/RuneLite.jar -O $CRAFT_PART_SRC/RuneLite.jar
      echo "b73561c714ad58984669f0b909731d4cc4c6bacdbf07d227006243d1b566138b $CRAFT_PART_SRC/RuneLite.jar" | sha256sum --check || exit 1 # Check hash manually, due to nil plugin
    override-build: |
      cp $CRAFT_PART_BUILD/RuneLite.jar $CRAFT_PART_INSTALL/RuneLite.jar
      chmod +x $CRAFT_PART_INSTALL/RuneLite.jar

  alsa-pulseaudio:
    plugin: dump
    source: .
    override-pull: |
      mkdir etc -p
      cat > etc/asound.conf <<EOF
      pcm.!default {
          type pulse
          fallback "sysdefault"
          hint {
              show on
              description "Default ALSA Output (currently PulseAudio Sound Server)"
          }
      }
      ctl.!default {
          type pulse
          fallback "sysdefault"
      }
      EOF

layout:
  /usr/lib/$SNAPCRAFT_ARCH_TRIPLET/alsa-lib:
    bind: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/alsa-lib

apps:
  runelite:
    command: bin/java -jar $SNAP/RuneLite.jar
    plugs:
      - desktop
      - desktop-legacy
      - network
      - audio-playback
      - x11
      - opengl

    extensions: [ gnome ]
    environment:
      _JAVA_OPTIONS: -Duser.home="$SNAP_USER_COMMON"
      ALSA_CONFIG_PATH: "$SNAP/etc/asound.conf"
